package com.arm.legv8simulator.client.lexer;

import java.util.ArrayList;

import com.arm.legv8simulator.client.instruction.Mnemonic;
import com.arm.legv8simulator.client.parser.Parser;

/**
 * The <code>TextLine</code> class is used to manipulate a line of LEGv8 source code.
 * <p>
 * Operations include: 
 * <ul>
 * 	<li> Invoking the <code>Lexer</code> and <code>Parser</code>
 * 	<li> Code formatting
 * </ul>
 * 
 * @author Jonathan Wright, 2016
 */
public class TextLine {

	/**
	 * @param line	a line of LEGv8 source code from the text editor
	 */
	public TextLine(String line) {
		this.line = line;
		removeComment();
	}
	
	private void removeComment() {
		int commentIdentifierIndex = line.indexOf("//");
		if (commentIdentifierIndex != -1) {
			comment = line.substring(commentIdentifierIndex);
			lineNoComment = line.substring(0, commentIdentifierIndex);
		} else {
			lineNoComment = line;
		}
	}
	
	/**
	 * Invokes the <code>Lexer</code> on the line of source code to produce a list of tokens
	 * 
	 * @see Lexer
	 */
	public void tokenize() {
		tokens = Lexer.lex(lineNoComment);
	}
	
	/**
	 * Invokes the <code>Parser</code> on the list of tokens generated by the <code>Lexer</code>
	 * 
	 * @return	the error message from the <code>Parser</code>; <code>null</code> if no error present.
	 */
	/** Returns the directive name (e.g. {@code ".data"}) for directive lines, or {@code null} otherwise. */
	public String getDirectiveName() {
		return directiveName;
	}

	private String parseDirective() {
		String trimmed = lineNoComment.trim();
		String[] parts = trimmed.split("[ \t]+", 2);
		String name = parts[0].toLowerCase();
		String args = parts.length > 1 ? parts[1].trim() : "";
		directiveName = name;
		switch (name) {
		case ".text":   return parseTextDirective(args);
		case ".data":   return parseDataDirective(args);
		case ".global": return parseGlobalDirective(args);
		case ".arch":   return parseArchDirective(args);
		case ".type":   return parseTypeDirective(args);
		case ".size":   return parseSizeDirective(args);
		case ".byte":   return parseByteDirective(args);
		default: return "Unknown directive: '" + parts[0] + "'";
		}
	}

	private String parseTextDirective(String args) {
		if (!args.isEmpty()) {
			return "Directive '.text' takes no arguments";
		}
		return null;
	}

	private String parseDataDirective(String args) {
		if (!args.isEmpty()) {
			return "Directive '.data' takes no arguments";
		}
		return null;
	}

	private String parseGlobalDirective(String args) {
		if (args.isEmpty()) {
			return "Directive '.global' requires a symbol name";
		}
		if (!isValidIdentifier(args)) {
			return "Directive '.global': invalid symbol name '" + args + "'";
		}
		return null;
	}

	// Accepts armv8-a, armv8-a+fp+simd, armv8.1-a, armv8.2-a, aarch64, etc.
	// Rejects 32-bit architectures (armv7, armv6, ...).
	private String parseArchDirective(String args) {
		if (args.isEmpty()) {
			return "Directive '.arch' requires an architecture name";
		}
		String base = args.toLowerCase();
		if (!base.startsWith("armv8") && !base.startsWith("armv9") && !base.startsWith("aarch64")) {
			return "Incompatible architecture '" + args + "': simulator requires ARMv8-A (64-bit) or later";
		}
		return null;
	}

	// Expects:  .type  <symbol>, %function  (or #function, %object, etc.)
	private String parseTypeDirective(String args) {
		if (args.isEmpty()) {
			return "Directive '.type' requires arguments";
		}
		int comma = args.indexOf(',');
		if (comma < 0) {
			return "Directive '.type' expects '<symbol>, <type>'";
		}
		String symbol = args.substring(0, comma).trim();
		String type   = args.substring(comma + 1).trim();
		if (!isValidIdentifier(symbol)) {
			return "Directive '.type': invalid symbol name '" + symbol + "'";
		}
		if (type.isEmpty() || (type.charAt(0) != '%' && type.charAt(0) != '#')) {
			return "Directive '.type': type specifier must start with '%' or '#' (e.g. '%function')";
		}
		for (int i = 1; i < type.length(); i++) {
			char c = type.charAt(i);
			if (!Character.isLetter(c) && c != '_') {
				return "Directive '.type': invalid type specifier '" + type + "'";
			}
		}
		return null;
	}

	// Expects:  .size  <symbol>, <size_expr>
	private String parseSizeDirective(String args) {
		if (args.isEmpty()) {
			return "Directive '.size' requires arguments";
		}
		int comma = args.indexOf(',');
		if (comma < 0) {
			return "Directive '.size' expects '<symbol>, <size>'";
		}
		String symbol = args.substring(0, comma).trim();
		if (!isValidIdentifier(symbol)) {
			return "Directive '.size': invalid symbol name '" + symbol + "'";
		}
		if (args.substring(comma + 1).trim().isEmpty()) {
			return "Directive '.size': missing size value";
		}
		return null;
	}

	// Expects:  .byte  val, val, ...  where each val is a char literal or integer.
	private String parseByteDirective(String args) {
		if (args.isEmpty()) {
			return "Directive '.byte' requires at least one value";
		}
		String[] values = args.split(",");
		byte[] bytes = new byte[values.length];
		for (int i = 0; i < values.length; i++) {
			String val = values[i].trim();
			try {
				bytes[i] = parseByteValue(val);
			} catch (IllegalArgumentException e) {
				return "Directive '.byte': " + e.getMessage();
			}
		}
		dataBytes = bytes;
		return null;
	}

	private static byte parseByteValue(String val) throws IllegalArgumentException {
		// Character literal: 'x' or '\n' etc.
		if (val.startsWith("'") && val.endsWith("'") && val.length() >= 3) {
			String inner = val.substring(1, val.length() - 1);
			if (inner.length() == 1) {
				return (byte) inner.charAt(0);
			}
			if (inner.length() == 2 && inner.charAt(0) == '\\') {
				switch (inner.charAt(1)) {
				case 'n':  return (byte) '\n';
				case 't':  return (byte) '\t';
				case 'r':  return (byte) '\r';
				case '0':  return (byte) 0;
				case '\\': return (byte) '\\';
				case '\'': return (byte) '\'';
				default: throw new IllegalArgumentException("unknown escape '\\" + inner.charAt(1) + "'");
				}
			}
			throw new IllegalArgumentException("invalid character literal '" + val + "'");
		}
		// Numeric (decimal or hex)
		try {
			int n = Integer.decode(val);
			if (n < -128 || n > 255) {
				throw new IllegalArgumentException("value " + val + " out of byte range (-128..255)");
			}
			return (byte) n;
		} catch (NumberFormatException e) {
			throw new IllegalArgumentException("invalid byte value '" + val + "'");
		}
	}

	/** Returns the parsed byte values for a {@code .byte} directive, or {@code null} for all other lines. */
	public byte[] getDataBytes() {
		return dataBytes;
	}

	private static boolean isValidIdentifier(String s) {
		if (s.isEmpty()) return false;
		char first = s.charAt(0);
		if (!Character.isLetter(first) && first != '_') return false;
		for (int i = 1; i < s.length(); i++) {
			char c = s.charAt(i);
			if (!Character.isLetterOrDigit(c) && c != '_') return false;
		}
		return true;
	}

	private byte[]  dataBytes     = null;
	private String  directiveName = null;

	public String parse() {
		if (lineNoComment.trim().startsWith(".")) {
			return parseDirective();
		}
		String error = Parser.parseLine(tokens);
		parsed = (error == null);
		if (parsed) {
			decodeLine();
		}
		return error;
	}

	/*
	 * Called only when line parsed correctly
	 * Used to set each of the label, mnemonic, args and comment fields
	 */
	private void decodeLine() {
		for (Token t : tokens) {
			switch (t.getType()) {
			case WHITESPACE : break;
			case COMMA : break;
			case LBRACKET : break;
			case RBRACKET : break;
			case LABEL : label = t.getData().substring(0, t.getData().length()-1); break;
			case XREGISTER : args.add(t.getData()); break;
			case WREGISTER : args.add(t.getData()); break;
			case SREGISTER : args.add(t.getData()); break;
			case DREGISTER : args.add(t.getData()); break;
			case IMMEDIATE : args.add(t.getData()); break;
			case IDENTIFIER : args.add(t.getData()); break;
			case RELOCATION : args.add(t.getData()); break;
			// following case should never occur - parser never accepts ERROR tokens
			case ERROR : comment += "something has gone very wrong for this to happen!"; break;
			default : 
				if (mnemonic == null) {
					mnemonic = Mnemonic.fromString(t.getData().trim());
					mneType = t.getType();
				} else {
					args.add(t.getData().trim());
				}
			}
		}
	}
	
	/**
	 * @return the formatted line of LEGv8 source code. If the code could not be parsed, 
	 * it will be returned as entered.
	 */
	public String getLine() {
		if (!parsed) {
			return this.line;
		}
		String line = "";
		if (label != null) { 
			line += label + ":";
		}
		if (mnemonic != null) {
			line += "\t" + mnemonic.nameUpper + "\t";
		}
		if (args.size() != 0) {
			line += formatArgs();
		}
		if (line.isEmpty()) {
			return this.line;
		} else {
			if (comment != null) {
				line += "\t" + comment;
			}
		}
		return line;
	}
	
	/*
	 * Returns a string containing the instruction arguments appropriately formatted
	 * Format type is dictated by the instruction group
	 * See LEGv8_Grammar.ppt slides for description of instruction groups
	 */
	private String formatArgs() {
		switch (mneType) {
		case XMNEMONIC_R : 
			return formatRArgs();
		case XMNEMONIC_RR : 
			return formatRRArgs();
		case SMNEMONIC_RR : 
			return formatRRArgs();
		case DMNEMONIC_RR : 
			return formatRRArgs();
		case XMNEMONIC_RRR : 
			return formatRRRArgs();
		case SMNEMONIC_RRR : 
			return formatRRRArgs();
		case DMNEMONIC_RRR : 
			return formatRRRArgs();
		case XMNEMONIC_RI : 
			return formatRIArgs();
		case XMNEMONIC_RRI : 
			return formatRRIArgs();
		case XMNEMONIC_RM : 
			return formatRMArgs();
		case SMNEMONIC_RM : 
			return formatRMArgs();
		case DMNEMONIC_RM : 
			return formatRMArgs();
		case XMNEMONIC_RRM : 
			return formatRRMArgs();
		case XMNEMONIC_RISI : 
			return formatRISIArgs();
		case MNEMONIC_L : 
			return formatLArgs();
		case XMNEMONIC_RL : 
			return formatRLArgs();
		default : return "Args formatting Failed.";
		}
	}
	
	private String formatRArgs() {
		return args.get(0);
	}
	
	private String formatRRArgs() {
		return args.get(0) + ", " + args.get(1);
	}
	
	private String formatRRRArgs() {
		return args.get(0) + ", " + args.get(1) + ", " + args.get(2);
	}
	
	private String formatRIArgs() {
		return args.get(0) + ", " + args.get(1);
	}
	
	private String formatRRIArgs() {
		return args.get(0) + ", " + args.get(1) + ", " + args.get(2);
	}
	
	private String formatRMArgs() {
		if (args.size() == 2) {
			return args.get(0) + ", [" + args.get(1) + "]";
		} else {
			return args.get(0) + ", [" + args.get(1) + ", " + args.get(2) + "]";
		}
	}
	
	private String formatRRMArgs() {
		if (args.size() == 3) {
			return args.get(0) + ", " + args.get(1) + ", [" + args.get(2) + "]";
		} else {
			return args.get(0) + ", " + args.get(1) + ", [" + args.get(2) + ", " + args.get(3) + "]";
		}
	}
	
	private String formatRISIArgs() {
		if (args.size() == 2) {
			return args.get(0) + ", " + args.get(1);
		} else {
			return args.get(0) + ", " + args.get(1) + ", LSL " + args.get(3);
		}
	}
	
	private String formatLArgs() {
		return args.get(0);
	}
	
	private String formatRLArgs() {
		return args.get(0) + ", " + args.get(1);
	}
	
	/**
	 * 
	 * @return	the label prefixing the instruction; <code>null</code> if none found
	 */
	public String getLabel() {
		return label;
	}
	
	/**
	 * 
	 * @return	the instruction mnemonic; <code>null</code> if none found
	 */
	public Mnemonic getMnemonic() {
		return mnemonic;
	}
	
	/**
	 * 
	 * @return	the list of instruction arguments; <code>null</code> if none found
	 */
	public ArrayList<String> getArgs() {
		return args;
	}
	
	/**
	 * Useful to see the output from the <code>Lexer</code>
	 * 
	 * @return the tokens in this <code>TextLine</code> object; each on a separate line
	 */
	public String getTokens() {
		String s = "";
		for (Token t: tokens) {
			s += t.toString() + "\n";
		}
		return s;
	}
	
	/**
	 * @return the number of lexical tokens found in this line of source code
	 */
	public int getNumTokens() {
		if (tokens == null) {
			return 0;
		} else {
			return tokens.size();
		}
	}
	
	private boolean parsed = false;
	private String line;
	private String lineNoComment;
	private ArrayList<Token> tokens = new ArrayList<Token>();
	private String label = null;
	private TokenType mneType = null;
	private Mnemonic mnemonic = null;
	private ArrayList<String> args = new ArrayList<String>();
	private String comment = null;
}
